# Generated by Django 5.1.7 on 2025-04-02 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={},
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='empresa',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='empresas',
            field=models.ManyToManyField(related_name='funcionarios', to='tickets.empresa'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('suporte', 'Suporte'), ('cliente', 'Cliente')], max_length=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
