# Generated by Django 4.2.7 on 2025-04-02 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_funcionario_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='atribuido_para',
        ),
        migrations.AddField(
            model_name='ticket',
            name='atribuido_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_atribuidos', to='tickets.funcionario'),
        ),
    ]
