# Generated by Django 4.2.7 on 2025-04-03 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_remove_ticket_atribuido_para_ticket_atribuido_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alteracao', models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('atribuicao', 'Atribuição'), ('status', 'Alteração de Status'), ('prioridade', 'Alteração de Prioridade'), ('comentario', 'Comentário')], max_length=20)),
                ('descricao', models.TextField()),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='tickets.ticket')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Ticket',
                'verbose_name_plural': 'Históricos de Tickets',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
