# Generated by Django 4.2.7 on 2025-04-03 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_campopersonalizado_valorcampopersonalizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campopersonalizado',
            options={'verbose_name': 'Campo Personalizado', 'verbose_name_plural': 'Campos Personalizados'},
        ),
        migrations.AlterModelOptions(
            name='valorcampopersonalizado',
            options={'verbose_name': 'Valor de Campo Personalizado', 'verbose_name_plural': 'Valores de Campos Personalizados'},
        ),
        migrations.RemoveField(
            model_name='campopersonalizado',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='campopersonalizado',
            name='ordem',
        ),
        migrations.AddField(
            model_name='campopersonalizado',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campopersonalizado',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='valorcampopersonalizado',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='valorcampopersonalizado',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='opcoes',
            field=models.TextField(blank=True, help_text='Opções para campo do tipo seleção (uma por linha)', null=True),
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('data', 'Data'), ('booleano', 'Sim/Não'), ('selecao', 'Seleção')], max_length=20),
        ),
    ]
