# Generated by Django 4.2.7 on 2025-04-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_campopersonalizado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campopersonalizado',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Campo Personalizado', 'verbose_name_plural': 'Campos Personalizados'},
        ),
        migrations.AddField(
            model_name='campopersonalizado',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
