# Generated by Django 4.2.7 on 2025-04-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_campopersonalizado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campopersonalizado',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
