# Generated by Django 4.2.7 on 2025-04-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_campopersonalizado_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campopersonalizado',
            name='editavel',
            field=models.BooleanField(default=True, help_text='Se marcado, este campo poderá ser editado após a criação do ticket'),
        ),
    ]
