# Generated by Django 4.2.7 on 2025-04-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_campopersonalizado_editavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campopersonalizado',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
