# Generated by Django 4.2.7 on 2025-04-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_campopersonalizado_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campopersonalizado',
            name='atualizado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
