# Generated by Django 4.2.7 on 2025-04-04 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_campopersonalizado_atualizado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campopersonalizado',
            name='atualizado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
