# Generated by Django 4.2.7 on 2025-04-04 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_campopersonalizado_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorcampopersonalizado',
            name='atualizado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
