# Generated by Django 4.2.7 on 2025-04-04 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_campopersonalizado_new_atualizado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campopersonalizado',
            name='new_atualizado_em',
        ),
    ]
