# Generated by Django 4.2.7 on 2025-04-04 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0015_remove_campopersonalizado_new_atualizado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Anotações Técnicas')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_tecnicas', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_tecnicas', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Nota Técnica',
                'verbose_name_plural': 'Notas Técnicas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
