# Generated by Django 4.2.7 on 2025-04-04 02:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_remove_campopersonalizado_new_atualizado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da nota técnica')),
                ('equipamento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Equipamento relacionado')),
                ('solucao_aplicada', models.TextField(blank=True, null=True, verbose_name='Solução aplicada')),
                ('pendencias', models.TextField(blank=True, help_text='Itens pendentes ou que precisam de acompanhamento', null=True, verbose_name='Pendências')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_tecnicas', to='tickets.funcionario')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_tecnicas', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Nota Técnica',
                'verbose_name_plural': 'Notas Técnicas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
