# Generated by Django 4.2.7 on 2025-04-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_notatecnica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoticket',
            name='tipo_alteracao',
            field=models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('atribuicao', 'Atribuição'), ('status', 'Alteração de Status'), ('prioridade', 'Alteração de Prioridade'), ('comentario', 'Comentário'), ('nota_tecnica', 'Nota Técnica')], max_length=20),
        ),
    ]
