# Generated by Django 4.2.7 on 2025-04-05 22:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_historicoticket_tipo_alteracao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoticket',
            options={'ordering': ['-data_alteracao']},
        ),
        migrations.RemoveField(
            model_name='historicoticket',
            name='dados_anteriores',
        ),
        migrations.RemoveField(
            model_name='historicoticket',
            name='dados_novos',
        ),
        migrations.RemoveField(
            model_name='historicoticket',
            name='descricao',
        ),
        migrations.AddField(
            model_name='historicoticket',
            name='valor_anterior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicoticket',
            name='valor_novo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicoticket',
            name='tipo_alteracao',
            field=models.CharField(choices=[('status', 'Alteração de Status'), ('prioridade', 'Alteração de Prioridade'), ('atribuicao', 'Alteração de Atribuição'), ('atribuicao_multipla', 'Atribuição Múltipla'), ('edicao', 'Edição de Informações'), ('comentario', 'Comentário'), ('campo_personalizado', 'Campo Personalizado')], max_length=20),
        ),
        migrations.CreateModel(
            name='AtribuicaoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False, help_text='Indica se este funcionário é o principal responsável pelo ticket')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_atribuidos_multi', to='tickets.funcionario')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Atribuição de Ticket',
                'verbose_name_plural': 'Atribuições de Tickets',
                'ordering': ['-principal', '-criado_em'],
                'unique_together': {('ticket', 'funcionario')},
            },
        ),
    ]
