# Generated by Django 4.2.7 on 2025-04-06 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0018_alter_historicoticket_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCompartilhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do perfil')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do perfil')),
                ('is_padrao', models.BooleanField(default=False, help_text='Se marcado, este perfil será o padrão para a empresa', verbose_name='Perfil padrão')),
                ('incluir_notas_tecnicas', models.BooleanField(default=False, verbose_name='Incluir notas técnicas')),
                ('incluir_historico', models.BooleanField(default=False, verbose_name='Incluir histórico')),
                ('incluir_comentarios', models.BooleanField(default=True, verbose_name='Incluir comentários')),
                ('incluir_campos_personalizados', models.BooleanField(default=True, verbose_name='Incluir campos personalizados')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_compartilhamento_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_compartilhamento', to='tickets.empresa')),
            ],
            options={
                'verbose_name': 'Perfil de Compartilhamento',
                'verbose_name_plural': 'Perfis de Compartilhamento',
                'ordering': ['-is_padrao', 'nome'],
                'unique_together': {('nome', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='CampoPerfilCompartilhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_campo', models.CharField(choices=[('basico', 'Campo Básico'), ('personalizado', 'Campo Personalizado')], default='basico', max_length=20)),
                ('nome_campo', models.CharField(max_length=100, verbose_name='Nome do campo')),
                ('ordem', models.IntegerField(default=0)),
                ('campo_personalizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfis_compartilhamento', to='tickets.campopersonalizado')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='tickets.perfilcompartilhamento')),
            ],
            options={
                'verbose_name': 'Campo de Perfil de Compartilhamento',
                'verbose_name_plural': 'Campos de Perfil de Compartilhamento',
                'ordering': ['ordem', 'nome_campo'],
                'unique_together': {('perfil', 'nome_campo')},
            },
        ),
    ]
