# Generated by Django 4.2.7 on 2025-04-06 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_perfilcompartilhamento_campoperfilcompartilhamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cor', models.CharField(default='primary', help_text='Nome da cor Bootstrap (primary, success, danger, etc)', max_length=20)),
                ('icone', models.CharField(default='fa-ticket-alt', help_text='Nome do ícone FontAwesome', max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='tickets.empresa')),
            ],
            options={
                'verbose_name': 'Categoria de Chamado',
                'verbose_name_plural': 'Categorias de Chamados',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('nome', 'empresa')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.categoriachamado'),
        ),
    ]
