# Generated by Django 5.2 on 2025-04-08 03:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_categoriachamado_ticket_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_usuarios', models.IntegerField(default=5, help_text='Número máximo de usuários que a empresa pode criar')),
                ('pode_criar_categorias', models.BooleanField(default=True, help_text='Se a empresa pode criar categorias de chamados')),
                ('pode_criar_campos_personalizados', models.BooleanField(default=True, help_text='Se a empresa pode criar campos personalizados')),
                ('pode_acessar_relatorios', models.BooleanField(default=True, help_text='Se a empresa pode acessar relatórios')),
                ('token_api', models.CharField(blank=True, help_text='Token para acesso à API', max_length=64, null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Se as funcionalidades administrativas da empresa estão ativas')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='tickets.empresa')),
            ],
            options={
                'verbose_name': 'Configuração de Empresa',
                'verbose_name_plural': 'Configurações de Empresas',
            },
        ),
    ]
