# Generated by Django 5.2 on 2025-04-09 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_empresaconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificar_todas', models.BooleanField(default=True, help_text='Receber todas as notificações')),
                ('notificar_atribuicao', models.BooleanField(default=True, help_text='Receber notificações quando um ticket for atribuído')),
                ('notificar_alteracao_status', models.BooleanField(default=True, help_text='Receber notificações quando o status de um ticket for alterado')),
                ('notificar_novo_comentario', models.BooleanField(default=True, help_text='Receber notificações quando um novo comentário for adicionado')),
                ('notificar_prioridade_alterada', models.BooleanField(default=True, help_text='Receber notificações quando a prioridade for alterada')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': 'Preferências de Notificação',
            },
        ),
    ]
