# Generated by Django 5.2 on 2025-04-10 00:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_preferenciasnotificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='tickets.categoriachamado')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_permitidas', to='tickets.funcionario')),
            ],
            options={
                'verbose_name': 'Permissão de Categoria',
                'verbose_name_plural': 'Permissões de Categorias',
                'unique_together': {('funcionario', 'categoria')},
            },
        ),
    ]
