# Generated by Django 5.2 on 2025-04-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_categoriapermissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoticket',
            name='dados_anteriores',
            field=models.JSONField(blank=True, help_text='Dados anteriores em formato JSON', null=True),
        ),
        migrations.AddField(
            model_name='historicoticket',
            name='dados_novos',
            field=models.JSONField(blank=True, help_text='Dados novos em formato JSON', null=True),
        ),
        migrations.AddField(
            model_name='historicoticket',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição textual da alteração', null=True),
        ),
        migrations.AlterField(
            model_name='historicoticket',
            name='tipo_alteracao',
            field=models.CharField(choices=[('status', 'Alteração de Status'), ('prioridade', 'Alteração de Prioridade'), ('atribuicao', 'Alteração de Atribuição'), ('atribuicao_multipla', 'Atribuição Múltipla'), ('edicao', 'Edição de Informações'), ('comentario', 'Comentário'), ('campo_personalizado', 'Campo Personalizado'), ('nota_tecnica', 'Nota Técnica')], max_length=20),
        ),
    ]
