# Generated by Django 5.2 on 2025-04-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_historicoticket_dados_anteriores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoticket',
            name='dados_anteriores',
        ),
        migrations.RemoveField(
            model_name='historicoticket',
            name='dados_novos',
        ),
        migrations.CreateModel(
            name='DetalheHistoricoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('anterior', 'Dado Anterior'), ('novo', 'Dado Novo')], max_length=10)),
                ('chave', models.CharField(max_length=100)),
                ('valor', models.TextField(blank=True, null=True)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='tickets.historicoticket')),
            ],
            options={
                'verbose_name': 'Detalhe de Histórico',
                'verbose_name_plural': 'Detalhes de Histórico',
            },
        ),
    ]
