# Generated by Django 5.2 on 2025-04-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_remove_historicoticket_dados_anteriores_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detalhehistoricoticket',
            index=models.Index(fields=['historico', 'tipo'], name='tickets_det_histori_e0bb99_idx'),
        ),
    ]
