# Generated by Django 5.2 on 2025-04-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_detalhehistoricoticket_tickets_det_histori_e0bb99_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verificado', models.BooleanField(default=False)),
                ('data_verificacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'E-mail verificado',
                'verbose_name_plural': 'E-mails verificados',
            },
        ),
    ]
