# Generated by Django 5.2 on 2025-04-22 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_emailverificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoVerificacaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('mensagem', models.TextField(blank=True, help_text='Mensagem opcional do solicitante', null=True)),
                ('verificado_ses', models.BooleanField(default=False, help_text='Indica se o email foi verificado no Amazon SES')),
                ('notificado', models.BooleanField(default=False, help_text='Indica se o usuário foi notificado que pode continuar o cadastro')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_verificacao', models.DateTimeField(blank=True, null=True)),
                ('data_notificacao', models.DateTimeField(blank=True, null=True)),
                ('token_cadastro', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Solicitação de Verificação de Email',
                'verbose_name_plural': 'Solicitações de Verificação de Email',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='numero_empresa',
            field=models.PositiveIntegerField(default=0, help_text='Número sequencial do ticket na empresa'),
        ),
        migrations.CreateModel(
            name='SequenciaTicketEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequencia_ticket', to='tickets.empresa')),
            ],
            options={
                'verbose_name': 'Sequência de Ticket por Empresa',
                'verbose_name_plural': 'Sequências de Tickets por Empresa',
            },
        ),
    ]
