# Generated by Django 5.2 on 2025-04-22 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_solicitacaoverificacaoemail_ticket_numero_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Chave API')),
                ('service', models.CharField(choices=[('n8n', 'n8n Workflow Automation'), ('webhook', 'Generic Webhook'), ('custom', 'Custom Integration')], default='n8n', max_length=20, verbose_name='Serviço')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('permissions', models.JSONField(blank=True, default=dict, verbose_name='Permissões')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Chave API',
                'verbose_name_plural': 'Chaves API',
                'ordering': ['-created_at'],
            },
        ),
    ]
