# Generated by Django 5.2 on 2025-04-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='N8nConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_enabled', models.BooleanField(default=False, verbose_name='Webhook ativado')),
                ('webhook_url', models.URLField(blank=True, max_length=255, verbose_name='URL do Webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Configuração n8n',
                'verbose_name_plural': 'Configurações n8n',
            },
        ),
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'Chave API', 'verbose_name_plural': 'Chaves API'},
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da chave'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='service',
            field=models.CharField(default='n8n', max_length=50, verbose_name='Serviço'),
        ),
    ]
