# Generated by Django 6.0.3 on 2026-03-17 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_n8nconfig_alter_apikey_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasnotificacao',
            name='habilitar_email',
            field=models.BooleanField(default=True, help_text='Habilitar notificações por e-mail'),
        ),
        migrations.AddField(
            model_name='preferenciasnotificacao',
            name='habilitar_push',
            field=models.BooleanField(default=True, help_text='Habilitar notificações push'),
        ),
        migrations.AddField(
            model_name='preferenciasnotificacao',
            name='notificar_alertas_sistema',
            field=models.BooleanField(default=False, help_text='Notificar sobre alertas do sistema'),
        ),
        migrations.AddField(
            model_name='preferenciasnotificacao',
            name='notificar_comentarios',
            field=models.BooleanField(default=True, help_text='Notificar sobre novos comentários/respostas'),
        ),
        migrations.AddField(
            model_name='preferenciasnotificacao',
            name='notificar_mudanca_status',
            field=models.BooleanField(default=True, help_text='Notificar sobre mudanças de status'),
        ),
        migrations.AddField(
            model_name='preferenciasnotificacao',
            name='notificar_novos_tickets',
            field=models.BooleanField(default=True, help_text='Notificar sobre novos tickets'),
        ),
        migrations.AlterField(
            model_name='preferenciasnotificacao',
            name='notificar_alteracao_status',
            field=models.BooleanField(default=True, help_text='Receber notificações quando o status de um ticket for alterado (LEGADO)'),
        ),
        migrations.AlterField(
            model_name='preferenciasnotificacao',
            name='notificar_atribuicao',
            field=models.BooleanField(default=True, help_text='Receber notificações quando um ticket for atribuído (LEGADO)'),
        ),
        migrations.AlterField(
            model_name='preferenciasnotificacao',
            name='notificar_novo_comentario',
            field=models.BooleanField(default=True, help_text='Receber notificações quando um novo comentário for adicionado (LEGADO)'),
        ),
        migrations.AlterField(
            model_name='preferenciasnotificacao',
            name='notificar_prioridade_alterada',
            field=models.BooleanField(default=True, help_text='Receber notificações quando a prioridade for alterada (LEGADO)'),
        ),
        migrations.AlterField(
            model_name='preferenciasnotificacao',
            name='notificar_todas',
            field=models.BooleanField(default=True, help_text='Receber todas as notificações (LEGADO)'),
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('plataforma', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='web', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Push',
                'verbose_name_plural': 'Tokens de Push',
            },
        ),
    ]
